"""Report models, markdown formatting, and storage engine."""

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from agent.config import get_settings


class ResearchReport(BaseModel):
    """Structured research report representation."""

    title: str
    date: str = Field(default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    report_type: str = "research"  # "research" or "digest"
    period: str = "Past 7 Days"
    tags: List[str] = Field(default_factory=lambda: ["AI", "Research"])
    executive_summary: List[str] = Field(default_factory=list)
    industry_news: List[Dict[str, Any]] = Field(default_factory=list)
    academic_papers: List[Dict[str, Any]] = Field(default_factory=list)
    open_source: List[Dict[str, Any]] = Field(default_factory=list)
    synthesis: str = ""


def format_report_markdown(report: ResearchReport) -> str:
    """Render a ResearchReport object into standardized markdown with frontmatter."""
    tags_str = ", ".join(report.tags)
    exec_bullets = "\n".join([f"- {bullet}" for bullet in report.executive_summary]) if report.executive_summary else "- No summary points provided."

    # Industry news section
    news_lines = []
    if report.industry_news:
        for item in report.industry_news:
            title = item.get("title", "Announcement")
            url = item.get("url", "#")
            details = item.get("details", "")
            news_lines.append(f"- **[{title}]({url})**\n  - {details}")
    else:
        news_lines.append("- No significant industry announcements reported in this window.")
    news_block = "\n".join(news_lines)

    # Academic papers section
    paper_lines = []
    if report.academic_papers:
        for paper in report.academic_papers:
            title = paper.get("title", "Research Paper")
            url = paper.get("url", "#")
            authors = ", ".join(paper.get("authors", [])) or "Various Authors"
            contrib = paper.get("contribution", "")
            paper_lines.append(f"- **[{title}]({url})** - *{authors}*\n  - {contrib}")
    else:
        paper_lines.append("- No new academic preprints indexed in this window.")
    paper_block = "\n".join(paper_lines)

    # Open source releases section
    os_lines = []
    if report.open_source:
        for item in report.open_source:
            name = item.get("name", "Model / Code")
            url = item.get("url", "#")
            details = item.get("details", "")
            os_lines.append(f"- **[{name}]({url})** - {details}")
    else:
        os_lines.append("- No new open-source weights or code releases flagged.")
    os_block = "\n".join(os_lines)

    synthesis_text = report.synthesis or "The field continues its rapid evolution across frontier models and open-source tooling."

    markdown = f"""---
title: "{report.title}"
date: {report.date}
type: {report.report_type}
tags: [{tags_str}]
---

# {report.title}
**Date:** {report.date} | **Period:** {report.period} | **Generated By:** DeepAgents AI Researcher

## Executive Summary
{exec_bullets}

## 1. Industry & Lab Announcements
{news_block}

## 2. Academic & Frontier Research
{paper_block}

## 3. Open Source Releases & Weights
{os_block}

## 4. Synthesis & Emerging Trends
{synthesis_text}
"""
    return markdown


def slugify(text: str) -> str:
    """Convert a title/string into a safe URL slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"[-\s]+", "-", text)


def normalize_to_report_markdown(
    raw_content: str,
    title: str = "AI Intelligence Report",
    report_type: str = "research",
    tags: Optional[List[str]] = None,
    period: str = "Past 7 Days",
    date_str: Optional[str] = None,
) -> str:
    """Ensure report content adheres to the standardized markdown schema with frontmatter."""
    today = date_str or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    chosen_tags = tags or ["AI", "Research"]

    # If already formatted with frontmatter, ensure basic consistency
    if raw_content.startswith("---") and "---" in raw_content[3:]:
        return raw_content

    # If raw content lacks frontmatter or is unformatted text, normalize into ResearchReport schema
    paragraphs = [p.strip() for p in raw_content.split("\n\n") if p.strip()]
    exec_summary = []
    if paragraphs:
        first_p = paragraphs[0]
        sentences = [s.strip() for s in first_p.split(".") if s.strip()]
        exec_summary = sentences[:3] if sentences else [first_p]

    report = ResearchReport(
        title=title,
        date=today,
        report_type=report_type,
        period=period,
        tags=chosen_tags,
        executive_summary=exec_summary or ["Automated research intelligence report."],
        synthesis=raw_content,
    )
    return format_report_markdown(report)


def save_report(
    report_md: str,
    slug: str = "report",
    report_type: str = "research",
    date_str: Optional[str] = None,
) -> Path:
    """Save report markdown content to the reports directory."""
    settings = get_settings()
    out_dir = Path(settings.reports_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    today = date_str or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    clean_slug = slugify(slug)

    if report_type == "digest":
        filename = f"{today}-ai-digest.md"
    else:
        filename = f"{today}-research-{clean_slug}.md"

    target_path = out_dir / filename
    target_path.write_text(report_md, encoding="utf-8")
    return target_path
